apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: weatherforecast-csharp
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: weatherforecast-csharp
    apps.tanzu.vmware.com/has-tests: true
spec:
  source:
    git:
      url: https://github.com/dbuchko/tap-demos.git
      ref:
        branch: main
    subPath: weatherforecast-csharp

# kubectl apply -f ../../config/test-pipeline.yaml -n dev

# tanzu apps workload list -n dev
# tanzu apps workload create -f ../../config/workload.yaml -n dev
# tanzu apps workload update -f ../../config/workload.yaml -n dev
# tanzu apps workload get weatherforecast-csharp -n dev
# tanzu apps workload tail weatherforecast-csharp -n dev --since 1h
# tanzu apps workload delete weatherforecast-csharp -n dev

# kubectl tree workload weatherforecast-csharp -n dev

# kubectl get deliverable -A 
# kubectl get deliverable weatherforecast-csharp -n dev
# kubectl get deliverable weatherforecast-csharp -o YAML -n dev >../run-primary/deliverable.yaml
# kubectl apply -f deliverable.yaml
# kubectl get deliverables -A 
# kubectl tree deliverable weatherforecast-csharp -n default
# kubectl delete deliverable weatherforecast-csharp -n default